services:
  - type: web
    name: ryzn-notes-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/google-credentials.json
    secrets:
      - name: google-credentials
        mountPath: /etc/secrets
